// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB-NTI2-oHH1CD2OnHPDwWwnZSk5C62CU',
    appId: '1:1068726012397:web:2d7b81d6cad47722763fe4',
    messagingSenderId: '1068726012397',
    projectId: 'flutter-base-structure-51c77',
    authDomain: 'flutter-base-structure-51c77.firebaseapp.com',
    storageBucket: 'flutter-base-structure-51c77.firebasestorage.app',
    measurementId: 'G-WH4RX0SEHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvYTv4KnG0W1LjHHMa7QDSLOYuldVkxM',
    appId: '1:1068726012397:android:dfaae4606c4382c0763fe4',
    messagingSenderId: '1068726012397',
    projectId: 'flutter-base-structure-51c77',
    storageBucket: 'flutter-base-structure-51c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzUc1kwwHgxHtdEWghNNI55jIecmwRkl8',
    appId: '1:1068726012397:ios:38c7d380c467084e763fe4',
    messagingSenderId: '1068726012397',
    projectId: 'flutter-base-structure-51c77',
    storageBucket: 'flutter-base-structure-51c77.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzUc1kwwHgxHtdEWghNNI55jIecmwRkl8',
    appId: '1:1068726012397:ios:38c7d380c467084e763fe4',
    messagingSenderId: '1068726012397',
    projectId: 'flutter-base-structure-51c77',
    storageBucket: 'flutter-base-structure-51c77.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB-NTI2-oHH1CD2OnHPDwWwnZSk5C62CU',
    appId: '1:1068726012397:web:7cc67978176da9e6763fe4',
    messagingSenderId: '1068726012397',
    projectId: 'flutter-base-structure-51c77',
    authDomain: 'flutter-base-structure-51c77.firebaseapp.com',
    storageBucket: 'flutter-base-structure-51c77.firebasestorage.app',
    measurementId: 'G-9F28WC05PM',
  );
}
